version: 2

release:
  github:
    owner: foresturquhart
    name: mc-jop-subdivider

before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - windows
      - darwin
    goarch:
      - amd64
    main: ./main.go
    binary: mc-jop-subdivider

archives:
  - formats: [ 'tar.gz' ]
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'